parameters:
    env(IDENTITY_SERVER_URL_EXTERNAL): 'https://peekabooauth.com'
    env(IDENTITY_SERVER_AUTH_PATH): '/identity/auth'
    env(IDENTITY_SERVER_LOGOUT_PATH): '/identity/logout'
    env(ROUTE_AFTER_REDIRECT): 'homepage'
    env(IDENTITY_SERVER_URL_INTERNAL): 'https://peekabooauth.com'
    env(PEEKABOO_APPLICATION_NAME): 'dev'
    #env(PEEKABOO_APPLICATION_SECRET): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Peekabooauth\PeekabooBundle\Controller\AuthController:
        tags: [ 'controller.service_arguments' ]

    Peekabooauth\PeekabooBundle\Controller\LogoutController:
        tags: [ 'controller.service_arguments' ]

    Peekabooauth\PeekabooBundle\Client\Client:
        bind:
            $identityServerUrlInternal: '%env(IDENTITY_SERVER_URL_INTERNAL)%'
            $app: '%env(PEEKABOO_APPLICATION_NAME)%'

    Peekabooauth\PeekabooBundle\ArgumentResolver\IdentityRequestResolver:
        tags:
            - { name: controller.request_value_resolver, priority: 255 }

    Peekabooauth\PeekabooBundle\Security\PeekabooAuthenticator: {public: true}
    Peekabooauth\PeekabooBundle\Security\ApiPeekabooAuthenticator: {public: true}
    Peekabooauth\PeekabooBundle\UserProvider\UserProvider: {public: true}
    Peekabooauth\PeekabooBundle\UserProvider\ApiUserProvider: {public: true}
    Peekabooauth\PeekabooBundle\Services\TargetBuilder: {public: true}

    Peekabooauth\PeekabooBundle\Services\AuthRedirectBuilder:
        bind:
            $identityServerUrlExternal: '%env(IDENTITY_SERVER_URL_EXTERNAL)%'
            $identityServerAuthPath: '%env(IDENTITY_SERVER_AUTH_PATH)%'
            $identityServerLogoutPath: '%env(IDENTITY_SERVER_LOGOUT_PATH)%'
            $routeAfterRedirect: '%env(ROUTE_AFTER_REDIRECT)%'
            $app: '%env(PEEKABOO_APPLICATION_NAME)%'
            $secret: '%env(PEEKABOO_APPLICATION_SECRET)%'


    Peekabooauth\PeekabooBundle\Services\TokenStorage:
        bind:
            $tokenName: '__peekaboo_token'

    Peekabooauth\PeekabooBundle\Listener\LogoutListener:
        tags:
            -   name: 'kernel.event_listener'
                event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
